# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0cuser_service\"Y\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"F\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"4\n\x12\x43reateUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\".\n\x10VerifyOtpRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\"3\n\x11VerifyOtpResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"E\n\x10LoginUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x10\n\x08provider\x18\x03 \x01(\t\"H\n\rLoginResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0b\n\x03jwt\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"4\n\x11LoginAdminRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x12LoginAdminResponse\x12\x0b\n\x03jwt\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc7\x02\n\x0bUserService\x12O\n\nCreateUser\x12\x1f.user_service.CreateUserRequest\x1a .user_service.CreateUserResponse\x12L\n\tVerifyOtp\x12\x1e.user_service.VerifyOtpRequest\x1a\x1f.user_service.VerifyOtpResponse\x12H\n\tLoginUser\x12\x1e.user_service.LoginUserRequest\x1a\x1b.user_service.LoginResponse\x12O\n\nLoginAdmin\x12\x1f.user_service.LoginAdminRequest\x1a .user_service.LoginAdminResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=36
  _globals['_CREATEUSERREQUEST']._serialized_end=125
  _globals['_USER']._serialized_start=127
  _globals['_USER']._serialized_end=197
  _globals['_CREATEUSERRESPONSE']._serialized_start=199
  _globals['_CREATEUSERRESPONSE']._serialized_end=251
  _globals['_VERIFYOTPREQUEST']._serialized_start=253
  _globals['_VERIFYOTPREQUEST']._serialized_end=299
  _globals['_VERIFYOTPRESPONSE']._serialized_start=301
  _globals['_VERIFYOTPRESPONSE']._serialized_end=352
  _globals['_LOGINUSERREQUEST']._serialized_start=354
  _globals['_LOGINUSERREQUEST']._serialized_end=423
  _globals['_LOGINRESPONSE']._serialized_start=425
  _globals['_LOGINRESPONSE']._serialized_end=497
  _globals['_LOGINADMINREQUEST']._serialized_start=499
  _globals['_LOGINADMINREQUEST']._serialized_end=551
  _globals['_LOGINADMINRESPONSE']._serialized_start=553
  _globals['_LOGINADMINRESPONSE']._serialized_end=603
  _globals['_USERSERVICE']._serialized_start=606
  _globals['_USERSERVICE']._serialized_end=933
# @@protoc_insertion_point(module_scope)
